app <- ShinyDriver$new("../", loadTimeout = 100000)
app$snapshotInit("demo-data")

app$uploadFile(peaks = system.file('target-app', 'sim_peaks.tsv', package = 'target'))
app$setInputs(peak_id_col = 'peak_name')
app$setInputs(distance = 100)
app$uploadFile(expression = system.file('target-app', 'sim_transcripts.tsv', package = 'target'))
app$setInputs(region_id = "tx_id")
app$setInputs(type = "Two")
app$setInputs(stat_id = "stat1")
app$setInputs(stat_id2 = "stat2")
app$uploadFile(genome = system.file('target-app', 'sim_genome.tsv', package = 'target'))
app$setInputs(genome_id_col = "name")

app$snapshot()
