app <- ShinyDriver$new("../", loadTimeout = 1e+06)
app$snapshotInit("one-factor")

app$uploadFile(peaks = system.file('extdata', '3656_peaks.bed.gz', package = 'target'))
app$uploadFile(expression = system.file('extdata', 'AR_diff_expr.tsv.gz', package = 'target'))
app$uploadFile(genome = system.file('extdata', 'hg19.refseq.gz', package = 'target'))
app$setInputs(stat_id = "t", wait_=FALSE, values_=FALSE)
app$setInputs(genome_id_col = "ID", wait_=FALSE, values_=FALSE)
app$setInputs(plot_rank = "stat", wait_=FALSE, values_=FALSE)
app$setInputs(plot_rank = "score_rank", wait_=FALSE, values_=FALSE)
app$setInputs(plot_group = "logFC", wait_=FALSE, values_=FALSE)
app$snapshot()
